# Generated by Django 4.2.21 on 2025-08-07 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.CharField(max_length=255, unique=True)),
                ('created_by', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('pinned', models.BooleanField(default=False)),
                ('input', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploadedinputfile')),
            ],
            options={
                'ordering': ['-pinned'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('result_file', models.CharField(blank=True, max_length=2048)),
                ('input_type', models.CharField(blank=True, max_length=24)),
                ('class_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploadedclassfile')),
                ('ground_truth_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploadedgroundtruthfile')),
                ('model_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploadedmodelfile')),
                ('wheel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.uploadedwheelfile')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.workflow')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('workflow', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('workflow_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='app.workflowstep')),
            ],
            options={
                'ordering': ['end_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('run_by', models.CharField(blank=True, max_length=255)),
                ('output', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.BooleanField(default=False)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflowrun', to='app.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField(null=True)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_workflow_run', to='app.workflowrun')),
                ('workflow_step_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_workflow_step_run', to='app.workflowsteprun')),
            ],
        ),
    ]
