# Generated by Django 4.2.21 on 2025-09-18 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='wheel_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='files.uploadedwheelfile'),
        ),
        migrations.AlterField(
            model_name='workflowsteprun',
            name='workflow_step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_steps', to='app.workflowstep'),
        ),
    ]
